language: python
python: 2.7
cache: pip
install:
    - pip install -e git+https://github.com/aiidateam/aiida-wannier90#egg=aiida-wannier90
    - pip install -e .[regen_default_paws,graphs]
    - pip install -r requirements-dev.txt
    - pip install --upgrade enum34
jobs:
    include:
        - stage: compliance
          script: pre-commit run --all-files
