language: python
python: 2.7
cache: pip
install:
    - pip install -e .
    - pip install -r requirements-dev.txt
    - pip uninstall pylint astroid enum34
    - pip install pylint
jobs:
    include:
        - stage: compliance
          script: pre-commit run --all-files
